### ISSUE TITLE
multi tumor/normal bams

### ISSUE THREAD

**Issue by husamia** [skandlab/VarNet#1]
Is it possible to call variants use multiple normal/tumor bams? for example, I have bams from several sites (A,B,C) that are not tumor and I want to call somatic against the site X. Normal A/B/C Tumor X

**Comment by kiranchari** [comment]
Thanks for your interest in our work. VarNet currently only supports single normal and single tumour bam as input. So they may have to be run separately (Normal A and Tumor X, Normal B and Tumor X, Normal C and Tumor X). Alternatively, you may choose to merge the normal bams (A+B+C) into a single file.
