### ISSUE TITLE
Is BQSR required for input BAM

### ISSUE THREAD

**Issue by ZJURenyi** [skandlab/VarNet#3]
Hello, I have two questions regarding the BAM preprocessing.
1) I used MarkDuplicatesSpark to mark but didn't remove the duplicates. Will it affect variant calling?
2) Is BQSR required?

Thank you!
Ren Yi

**Comment by kiranchari** [comment]
Hi Ren Yi,

1. I think that should be fine.
2. We do not run BQSR in our pre-processing pipeline. 

I can share the settings of our bcbio-nextgen pipeline if you would like to reproduce our process.

**Comment by ZJURenyi** [comment]
Hi [kiranchari](https://github.com/kiranchari),

Thank you so much for your prompt reply.

I will test on BAM with/without BQSR and update here.

Ren Yi

**Comment by kiranchari** [comment]
Hi @ZJURenyi, that would be great, thank you!

**Comment by fredsamhaak** [comment]
Hi @kiranchari,

I am doing somatic variant calling of tumor samples these days and trying to use VarNet. Would you please share the settings of your bcbio-nextgen pipeline for recommendation? Thanks a lot in advance.

He Shen

**Comment by fredsamhaak** [comment]
> 

Hi @kiranchari,

I am doing somatic variant calling of tumor samples these days and trying to use VarNet. Would you please share the settings of your bcbio-nextgen pipeline for reference? Thanks a lot in advance.

He Shen

**Comment by kiranchari** [comment]
Hi @fredsamhaak 

Sure, here is the YAML settings file we generally use. You may modify this based on your needs. 

[dna.hg38.yaml.txt](https://github.com/skandlab/VarNet/files/12035731/dna.hg38.yaml.txt)

**Comment by fredsamhaak** [comment]
Hi @kiranchari,

Sorry for the late response and thanks a lot!

He Shen
