### ISSUE TITLE
Error in VCF files

### ISSUE THREAD

**Issue by jakobjn** [skandlab/VarNet#5]
In the generated VCF files the columns headers are seperated by spaces instead of tabs. This inconsistency causes BCFtools to be unable to parse the header:

`bcftools view PC1-10.vcf` 
`[W::bcf_hdr_parse] Could not parse header line: #CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  SAMPLE`
`[E::bcf_hdr_parse] Could not parse the header, sample line not found`
`Failed to open PC1-10.vcf: could not parse header`

**Comment by kiranchari** [comment]
Hi @jakob1482, thanks for letting us know! 

We have fixed this in the latest commit. You may 'git pull' the latest commit or replace 'predict.py' in VarNet's root directory with the updated version here: https://github.com/skandlab/VarNet/blob/e385c4f12b9f2baf9359cffde78898ac21c3272e/predict.py

To re-generate the above VCF file, simply delete the VCF file in the output directory and re-run the predict.py step. Let us know if there are any further issues.
