### ISSUE TITLE
Issue running predict through Docker

### ISSUE THREAD

**Issue by Heather1999** [skandlab/VarNet#6]
Hello, thank you for developing such a useful tool; I recently successfully ran filter.py, however when I try to run predict.py, it kept telling me to run filter first.
The following are my codes:
`docker run -it --rm     -v /home/sealight1999/ASC_lifted/rmzero:/pikachu     -w /varnet     kiranchari/varnet:latest     python predict.py --sample_name /pikachu/AS_02_predict     --normal_bam /pikachu/AS_02N_BQSR.bam --tumor_bam /pikachu/AS_02T_BQSR.bam     --processes 2 --output_dir /pikachu/VarNet --reference /pikachu/GRCh38_no_alt.fna     --path_to_positions_to_predict /pikachu/VarNet/AS_02N/candidates`
And the warning I get is:
Candidate positions missing. Please run the filter script before predict.
What could be wrong? thank you!

**Comment by kiranchari** [comment]
Thanks for your interest @Heather1999. Please make sure you use the same `--sample_name` that you used when you ran `filter.py`. It looks like you used `AS_02N` when you ran filter.py but `/pikachu/AS_02_predict` when you are running `predict.py`.

You can leave out the `--path_to_positions_to_predict` argument as it is not used by `predict.py`. The script will automatically find the candidates in the sample output folder.

**Comment by Heather1999** [comment]
Brilliant! I just found out about that.
Thank you for your swift response!

**Comment by kiranchari** [comment]
Glad that's sorted out!
