### ISSUE TITLE
filter.py no such file or directory

### ISSUE THREAD

**Issue by Heather1999** [skandlab/VarNet#8]

**Comment by Heather1999** [comment]
Hello, the following are my codes; The filter.py worked smoothly but I am encountering issues with predict.py:
docker run -it --rm -v /home/sealight1999/ASC_lifted/rmzero/history/all_bam/:/pikachu -w /varnet kiranchari/varnet:latest /bin/bash -c "git pull; python predict.py --sample_name AS_02N --normal_bam /pikachu/AS_02N_BQSR.bam --tumor_bam /pikachu/AS_02T_BQSR.bam     --processes 2 --output_dir /pikachu/ --reference /pikachu/VarNet/GRCh38_no_alt.fna --path_to_positions_to_predict /pikachu/VarNet/
The error says fatal: Not a git repository (or any of the parent directories): .git
python: can't open file 'predict.py': [Errno 2] No such file or directory.
What could be the problem? thank you!

**Comment by kiranchari** [comment]
@Heather1999 If you downloaded the docker image again, please update the working directory to `-w /VarNet` in your command as the code directory was changed. The example docker command in the README has also been changed accordingly.

**Comment by Heather1999** [comment]
Thank you for your swift reply; So I did changed the N to capital letter but still getting the same error:
code:
`docker run -it --rm -v /home/sealight1999/ASC_lifted/rmzero/history/all_bam/:/pikachu -w /varNet kiranchari/varnet:latest /bin/bash -c "git pull; python predict.py --sample_name AS_02N --normal_bam /pikachu/AS_02N_BQSR.bam --tumor_bam /pikachu/AS_02T_BQSR.bam --processes 2 --output_dir /pikachu/ --reference /pikachu/VarNet/GRCh38_no_alt.fna --path_to_positions_to_predict /pikachu/VarNet/"`
error:
fatal: Not a git repository (or any of the parent directories): .git
python: can't open file 'predict.py': [Errno 2] No such file or directory

**Comment by kiranchari** [comment]
It should be `-w /VarNet`, both `V` and `N` should be capitalized

**Comment by Heather1999** [comment]
Ah! Don't know how I missed that. Issue fixed, thank you so much!
